/**
 * Report builders (pure, dependency-free). Render the internal ops report as
 * Markdown / CSV / JSON for export (super-plan §14).
 */

export interface ReportWorkflowRow {
  name: string
  status: string
  healthScore?: number | null
  riskScore?: number | null
  businessValue?: number | null
  manualHoursSaved?: number | null
  apiCost?: number | null
}

export interface OpsReport {
  generatedAt: string
  totals: {
    workflows: number
    active: number
    failing: number
    atRisk: number
    manualHoursSaved: number
    apiCostEstimate: number
    avgBusinessValue: number
  }
  topValuable: ReportWorkflowRow[]
  leastReliable: ReportWorkflowRow[]
  mostExpensive: ReportWorkflowRow[]
}

function csvCell(v: unknown): string {
  const s = v == null ? '' : String(v)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

export function rowsToCsv(rows: ReportWorkflowRow[]): string {
  const header = ['name', 'status', 'healthScore', 'riskScore', 'businessValue', 'manualHoursSaved', 'apiCost']
  const lines = [header.join(',')]
  for (const r of rows) {
    lines.push([r.name, r.status, r.healthScore, r.riskScore, r.businessValue, r.manualHoursSaved, r.apiCost].map(csvCell).join(','))
  }
  return lines.join('\n')
}

export function buildOpsReportMarkdown(r: OpsReport): string {
  const section = (title: string, rows: ReportWorkflowRow[], col: keyof ReportWorkflowRow) => {
    const lines = [`## ${title}`, '', '| Workflow | Status | ' + String(col) + ' |', '| --- | --- | --- |']
    for (const row of rows.slice(0, 10)) lines.push(`| ${row.name} | ${row.status} | ${row[col] ?? '—'} |`)
    return lines.join('\n')
  }
  return [
    `# n8n Automation — Internal Ops Report`,
    `_Generated ${r.generatedAt}. Hours/cost are estimates._`,
    '',
    '## Totals',
    `- Workflows: ${r.totals.workflows}`,
    `- Active: ${r.totals.active}`,
    `- Failing: ${r.totals.failing}`,
    `- At risk: ${r.totals.atRisk}`,
    `- Est. manual hours saved: ${r.totals.manualHoursSaved}`,
    `- Est. API cost: $${r.totals.apiCostEstimate}`,
    `- Avg business value: ${r.totals.avgBusinessValue}`,
    '',
    section('Top 10 most valuable', r.topValuable, 'businessValue'),
    '',
    section('Top 10 least reliable', r.leastReliable, 'riskScore'),
    '',
    section('Top 10 most expensive', r.mostExpensive, 'apiCost'),
    '',
    '_Generated by the n8n automation dashboard._',
  ].join('\n')
}
