/**
 * Deterministic workflow documentation generator (pure, dependency-free).
 * Input MUST already be redacted by the caller (routes run redactAll first),
 * so this never sees raw secrets. AI-enhanced docs layer on top later.
 */

interface WorkflowNode {
  name?: string
  type?: string
  credentials?: Record<string, { name?: string }>
}

interface WorkflowJson {
  id?: string
  name?: string
  active?: boolean
  nodes?: WorkflowNode[]
  tags?: Array<{ name?: string } | string>
  connections?: Record<string, unknown>
}

const TRIGGER_RE = /trigger|webhook|cron|schedule|pollwhen|interval/i

function shortType(t: string): string {
  // n8n-nodes-base.httpRequest -> httpRequest
  const parts = t.split('.')
  return parts[parts.length - 1] || t
}

export function generateWorkflowDocs(wf: WorkflowJson): string {
  const nodes = Array.isArray(wf.nodes) ? wf.nodes : []
  const tags = (Array.isArray(wf.tags) ? wf.tags : [])
    .map((t) => (typeof t === 'string' ? t : t?.name || ''))
    .filter(Boolean)

  const triggers = nodes.filter((n) => TRIGGER_RE.test(n.type || ''))
  const services = new Set<string>()
  for (const n of nodes) {
    for (const credType of Object.keys(n.credentials || {})) services.add(credType)
    const t = shortType(n.type || '')
    if (/http|api|graphql|webhook/i.test(t)) services.add(t)
  }

  const typeCounts = new Map<string, number>()
  for (const n of nodes) {
    const t = shortType(n.type || 'unknown')
    typeCounts.set(t, (typeCounts.get(t) || 0) + 1)
  }

  const lines: string[] = []
  lines.push(`# ${wf.name || 'Untitled workflow'}`)
  lines.push('')
  lines.push(`- **Status:** ${wf.active ? 'active' : 'inactive'}`)
  if (wf.id) lines.push(`- **n8n ID:** \`${wf.id}\``)
  lines.push(`- **Nodes:** ${nodes.length}`)
  if (tags.length) lines.push(`- **Tags:** ${tags.join(', ')}`)
  lines.push('')

  lines.push('## Triggers')
  if (triggers.length === 0) {
    lines.push('_No trigger nodes detected (manual or sub-workflow)._')
  } else {
    for (const t of triggers) lines.push(`- ${t.name || '(unnamed)'} — \`${shortType(t.type || '')}\``)
  }
  lines.push('')

  lines.push('## External services')
  if (services.size === 0) lines.push('_None detected._')
  else for (const s of [...services].sort()) lines.push(`- ${s}`)
  lines.push('')

  lines.push('## Node inventory')
  for (const [type, count] of [...typeCounts.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${type} × ${count}`)
  }
  lines.push('')
  lines.push('_Generated by the n8n dashboard. Review and edit before sharing._')

  return lines.join('\n')
}
