#!/usr/bin/env node
/*
 * Baseline collector for PR #0.
 * Uses dependency-free checks by default and records when optional browser tooling is unavailable.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { spawnSync } from 'node:child_process'

const outDir = resolve(process.cwd(), 'tests/__screenshots__/baseline')
const observationsPath = resolve(outDir, 'observations.json')
const summaryPath = resolve(outDir, 'SUMMARY.md')
const baseUrl = process.env.DASHBOARD_BASE_URL || process.env.APP_BASE_URL
const checkedAt = new Date().toISOString()

if (!baseUrl) {
  throw new Error('Set DASHBOARD_BASE_URL or APP_BASE_URL before running the baseline script.')
}

mkdirSync(outDir, { recursive: true })

function run(command, args) {
  const result = spawnSync(command, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })
  return {
    command: [command, ...args].join(' '),
    exitCode: result.status,
    stdoutBytes: Buffer.byteLength(result.stdout || '', 'utf8'),
    stderrBytes: Buffer.byteLength(result.stderr || '', 'utf8'),
  }
}

async function fetchStatus(path) {
  const started = Date.now()
  try {
    const response = await fetch(`${baseUrl}${path}`, { redirect: 'manual' })
    const ok = path === '/api/health'
      ? response.status === 200 && response.ok
      : response.ok || [301, 302, 303, 307, 308].includes(response.status)

    return {
      path,
      status: response.status,
      ok,
      location: response.headers.get('location') || undefined,
      latencyMs: Date.now() - started,
    }
  } catch (error) {
    return {
      path,
      status: 0,
      ok: false,
      error: error instanceof Error ? error.name : 'FetchError',
      latencyMs: Date.now() - started,
    }
  }
}

const localCommands = [run('npm', ['test'])]
const routes = await Promise.all(['/login', '/', '/api/health'].map(fetchStatus))
const probeRun = run('node', ['scripts/probe-instance.mjs'])

if (probeRun.exitCode !== 0 || !existsSync(resolve(process.cwd(), 'tests/__screenshots__/baseline/n8n-probe.json'))) {
  throw new Error(`n8n probe artifact was not created. Command=${probeRun.command} exit=${probeRun.exitCode}`)
}

let browserCapture = {
  available: false,
  note: 'Playwright is not installed as a project dependency in PR #0; screenshots are deferred to CI/agent browser verification.',
}
try {
  await import('@playwright/test')
  browserCapture = {
    available: true,
    note: 'Playwright package is available; run browser visual baselines with the project-specific QA command in a later CI PR.',
  }
} catch {
  // optional dependency absent; recorded above
}

const observations = {
  checkedAt,
  baseUrl,
  routes,
  localCommands,
  probeRun: {
    command: probeRun.command,
    exitCode: probeRun.exitCode,
  },
  browserCapture,
  viewportsPlanned: ['360x780', '768x1024', '1024x768', '1440x900', '1920x1080'],
  themesPlanned: ['dark', 'light'],
  notes: [
    'PR #0 intentionally keeps the baseline lightweight and dependency-free.',
    'No screenshots contain secrets because no screenshots are generated by this script unless browser tooling is explicitly installed later.',
    'n8n probe output is sanitized and stored in n8n-probe.json.',
  ],
}

writeFileSync(observationsPath, `${JSON.stringify(observations, null, 2)}\n`)

const issueLines = []
for (const route of routes) {
  if (!route.ok) issueLines.push(`- Route ${route.path} returned status ${route.status}.`)
}
if (probeRun.exitCode !== 0) issueLines.push('- `scripts/probe-instance.mjs` failed; re-run the probe command to see sanitized error details.')
if (!browserCapture.available) issueLines.push('- Browser screenshot capture is not yet wired into project dependencies/CI.')

writeFileSync(
  summaryPath,
  `# PR #0 Baseline Summary\n\n` +
    `Checked at: ${checkedAt}\n\n` +
    `Base URL: ${baseUrl}\n\n` +
    `## Route baseline\n\n` +
    routes.map((route) => `- ${route.path}: status ${route.status}${route.location ? ` -> ${route.location}` : ''}, ${route.latencyMs}ms`).join('\n') +
    `\n\n## Local checks\n\n` +
    localCommands.map((cmd) => `- \`${cmd.command}\`: exit ${cmd.exitCode}`).join('\n') +
    `\n- \`${probeRun.command}\`: exit ${probeRun.exitCode}\n` +
    `\n## n8n probe\n\nSee \`n8n-probe.json\`. It contains only sanitized status/evidence metadata.\n\n` +
    `## Browser baseline\n\n${browserCapture.note}\n\n` +
    `## Top issues / follow-ups\n\n${issueLines.length ? issueLines.slice(0, 25).join('\n') : '- No blocking baseline issue recorded by the dependency-free baseline script.'}\n`
)

console.log(`Wrote ${observationsPath}`)
console.log(`Wrote ${summaryPath}`)
